### ISSUE TITLE
Could you provide the whole dataset to reproduce the experiment in the paper, please?

### ISSUE THREAD

**Issue by Gift-OYS** [HannesStark/CodonMPNN#1]
Could you provide the whole dataset to reproduce the experiment in the paper, please?

**Comment by HannesStark** [comment]
Here is a link to download the .csv file for the whole training validation and test data: https://publbuck.s3.us-east-2.amazonaws.com/afdb_with_groupings.csv
It contains AFDB ids for representatives of mmseqs clusters with a maximum 30% sequence identity. The train, val, test split is a random split.

Unfortunately, I cannot upload all the .pdb files somewhere due to the dataset size. You can download the pdb files from AFDB using their api and code similar to this:

```
import requests
url = f"https://alphafold.ebi.ac.uk/files/{afdb_id}.pdb"
response = requests.get(url)

if response.status_code == 200:
    with open(f'{afdb_id}.pdb', 'wb') as pdb_file:
        pdb_file.write(response.content)
```
